spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kurly
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: simplemailsender100@gmail.com
    password: wdjlxzpzykhmjakx
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
